=== jmnb-sdbg-edi/cardamom/tags/start/SystemMngt/platformadmin/c++/data/CdmwPlatformMngtSystem.dtd
<!-- ===================================================================== -->
<!--
 * This file is part of CARDAMOM (R) which is jointly developed by THALES 
 * and SELEX-SI. 
 * 
 * It is derivative work based on PERCO Copyright (C) THALES 2000-2003. 
 * All rights reserved.
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it under 
 * the terms of the GNU Library General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your 
 * option) any later version. 
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public 
 * License for more details. 
 * 
 * You should have received a copy of the GNU Library General 
 * Public License along with CARDAMOM; see the file COPYING. If not, write to 
 * the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
-->
<!-- ===================================================================== -->

<!-- Perco deployment file DTD (Thales ISR ) -->

<!-- ***************** -->
<!-- System definition -->
<!-- ***************** -->
<!ELEMENT System (
    Timeout,
    Host-monitoring,
    App-monitoring,
    Proc-monitoring,
    Service*,
    Entity*,
    Property*,
    Host*,
    Application*,
    Init-graph?,
    Stop-graph?,
    Run-set* )>
<!ATTLIST System
    Name CDATA #REQUIRED
	Port CDATA #REQUIRED
>

<!-- ******************************** -->
<!-- Timeout definition for processes -->
<!-- ******************************** -->
<!ELEMENT Timeout EMPTY>
<!ATTLIST Timeout
	Init CDATA #REQUIRED
	Run  CDATA #REQUIRED
	Stop CDATA #REQUIRED
>

<!-- ************************** -->
<!-- Host monitoring definition -->
<!-- ************************** -->
<!ELEMENT Host-monitoring EMPTY>
<!ATTLIST Host-monitoring
    Pull-interval CDATA #REQUIRED
    Pull-timeout  CDATA #REQUIRED
>

<!-- ********************************* -->
<!-- Application monitoring definition -->
<!-- ********************************* -->
<!ELEMENT App-monitoring EMPTY>
<!ATTLIST App-monitoring
    Pull-interval CDATA #REQUIRED
    Pull-timeout  CDATA #REQUIRED
>

<!-- ***************************** -->
<!-- Process monitoring definition -->
<!-- ***************************** -->
<!ELEMENT Proc-monitoring EMPTY>
<!ATTLIST Proc-monitoring
    Model ( NO_MONITORING |
            PULL_MONITORING_MODEL |
            PUSH_MONITORING_MODEL |
            FULL_MONITORING_MODEL )
            #REQUIRED
    Pull-interval CDATA #REQUIRED
    Pull-timeout  CDATA #REQUIRED
    Push-interval CDATA #REQUIRED
    Push-timeout  CDATA #REQUIRED
>

<!-- ****************** -->
<!-- Service definition -->
<!-- ****************** -->
<!ELEMENT Service EMPTY>
<!ATTLIST Service
	Name         CDATA #REQUIRED
	App-name     CDATA #REQUIRED
	Process-name CDATA #REQUIRED
>

<!-- ***************** -->
<!-- Entity definition -->
<!-- ***************** -->
<!ELEMENT Entity EMPTY>
<!ATTLIST Entity
	Name CDATA #REQUIRED
>

<!-- ******************* -->
<!-- Property definition -->
<!-- ******************* -->
<!ELEMENT Property EMPTY>
<!ATTLIST Property
	Name CDATA #REQUIRED
>

<!-- *************** -->
<!-- Host definition -->
<!-- *************** -->
<!ELEMENT Host (
    Host-monitoring?,
    Property* )>
<!ATTLIST Host
	Name            CDATA #REQUIRED
	App-exec-path   CDATA #REQUIRED
	Agent-exec-path CDATA #REQUIRED
	Probe-exec-path CDATA #REQUIRED
    Probe-port      CDATA #IMPLIED
    Probe-args      CDATA #IMPLIED
    Probe-run-dir   CDATA #IMPLIED
>

<!-- ********************** -->
<!-- Application definition -->
<!-- ********************** -->
<!ELEMENT Application (
    Timeout?,
    App-monitoring?,
    Proc-monitoring?,
    Service*,
    Entity*,
    Property*,
    ( Managed-process | Unmanaged-process )*,
    Init-graph?,
    Stop-graph? )>
<!ATTLIST Application
	Name          CDATA #REQUIRED
    Host-name     CDATA #REQUIRED
    Agent-port    CDATA #IMPLIED
    Agent-args    CDATA #IMPLIED
    Agent-run-dir CDATA #IMPLIED
    App-port      CDATA #IMPLIED
    App-args      CDATA #IMPLIED
    App-run-dir   CDATA #IMPLIED
>

<!-- ************************** -->
<!-- Managed process definition -->
<!-- ************************** -->
<!ELEMENT Managed-process (
    Init-step+,
    Run-timeout?,
    Stop-timeout?,
    Proc-monitoring?,
    Service*,
    Entity*,
    Property*,
    Activity-point* )>
<!ATTLIST Managed-process
	Name      CDATA #REQUIRED
	Host-name CDATA #REQUIRED
	Type      ( MANAGED-PROCESS |
                SERVICE-PROVIDER |
                COMPONENT-SERVER )
                #REQUIRED
	Autoended ( FALSE | TRUE ) #REQUIRED
	Exec-path CDATA #REQUIRED
    Port      CDATA #IMPLIED
	Args      CDATA #IMPLIED
	Run-dir   CDATA #IMPLIED
>

<!-- ******************** -->
<!-- Init step definition -->
<!-- ******************** -->
<!ELEMENT Init-step EMPTY>
<!ATTLIST Init-step
	Name    CDATA #REQUIRED
    Timeout CDATA #IMPLIED
>

<!-- ********************** -->
<!-- Run timeout definition -->
<!-- ********************** -->
<!ELEMENT Run-timeout EMPTY>
<!ATTLIST Run-timeout
    Timeout CDATA #REQUIRED
>

<!-- *********************** -->
<!-- Stop timeout definition -->
<!-- *********************** -->
<!ELEMENT Stop-timeout EMPTY>
<!ATTLIST Stop-timeout
    Timeout CDATA #REQUIRED
>

<!-- ************************* -->
<!-- Activity point definition -->
<!-- ************************* -->
<!ELEMENT Activity-point EMPTY>
<!ATTLIST Activity-point
    Name                CDATA #REQUIRED
    Monitoring-interval CDATA #REQUIRED
    Monitoring-timeout  CDATA #REQUIRED
>

<!-- *************************** -->
<!-- Unamaged process definition -->
<!-- *************************** -->
<!ELEMENT Unmanaged-process (
    Property* )>
<!ATTLIST Unmanaged-process
	Name      CDATA #REQUIRED
	Host-name CDATA #REQUIRED
	Autoended ( FALSE | TRUE ) #REQUIRED
	Exec-path CDATA #REQUIRED
    Port      CDATA #IMPLIED
	Args      CDATA #IMPLIED
	Run-dir   CDATA #IMPLIED
>

<!-- *************************** -->
<!-- Dependency graph definition -->
<!-- *************************** -->
<!ELEMENT Init-graph (
    Graph-element+,
    Graph-element-root+ )>
    
<!ELEMENT Stop-graph (
    Graph-element+,
    Graph-element-root+ )>
    
<!ELEMENT Graph-element (
    Graph-element-successor* )>
<!ATTLIST Graph-element
	Name CDATA #REQUIRED
	Step CDATA #IMPLIED
>

<!ELEMENT Graph-element-successor EMPTY>
<!ATTLIST Graph-element-successor
	Name CDATA #REQUIRED
	Step CDATA #IMPLIED
>

<!ELEMENT Graph-element-root EMPTY>
<!ATTLIST Graph-element-root
	Name CDATA #REQUIRED
	Step CDATA #IMPLIED
>

<!-- ****************** -->
<!-- Run set definition -->
<!-- ****************** -->
<!ELEMENT Run-set (
    Run-set-element+ )>
<!ATTLIST Run-set
	Name CDATA #REQUIRED
>
<!ELEMENT Run-set-element EMPTY>
<!ATTLIST Run-set-element
    Name CDATA #REQUIRED
>

<!-- ******************************* -->
<!-- Additional definitions used for -->
<!-- hot process modification        -->
<!-- ******************************* -->
<!ELEMENT Life-cycle (
    Init-step+,
    Run-timeout,
    Stop-timeout )>

=== jmnb-sdbg-edi/cardamom/FaultTolerance/valid/validationdata/data/V-FLT-012-1.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- ===================================================================== -->
<!--
 * This file is part of CARDAMOM (R) which is jointly developed by THALES
 * and SELEX-SI. It is derivative work based on PERCO Copyright (C) THALES
 * 2000-2003. All rights reserved.
 * 
 * Copyright (C) THALES 2004-2005. All rights reserved
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Library General Public License as published
 * by the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Library General Public
 * License along with CARDAMOM; see the file COPYING. If not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
-->
<!-- ===================================================================== -->


<!DOCTYPE System SYSTEM "CdmwPlatformMngtSystem.dtd">

<!-- ***************** -->
<!-- System definition -->
<!--                   -->
<!-- ***************** -->
<System Name="validation" Port="21869">

    <!-- Default timeouts for processes of the entire system -->
    <Timeout Init="20000" Run="20000" Stop="20000"/>

    <!-- Default monitorings for the entire system -->
    <Host-monitoring Pull-interval="10000" Pull-timeout="3000"/>
    <App-monitoring  Pull-interval="0" Pull-timeout="0"/>
    <Proc-monitoring Model="NO_MONITORING"
                     Pull-interval="0" Pull-timeout="0"
                     Push-interval="0" Push-timeout="0"/>

    <!-- Services of the system -->
    <Service Name="NamingAndRepositoryService"
             App-name="CdmwServices"
             Process-name="Repository"/>


    <!-- Hosts of the system -->
    <Host Name="@hostname1val@"
          App-exec-path="cdmw_platform_application"
          Agent-exec-path="cdmw_platform_agent"/>
    <Host Name="@hostname2val@"
          App-exec-path="cdmw_platform_application"
          Agent-exec-path="cdmw_platform_agent"/>
    <Host Name="@hostname3val@"
          App-exec-path="cdmw_platform_application"
          Agent-exec-path="cdmw_platform_agent"/>

    <!-- ********************** -->
    <!-- Application definition -->
    <!--                        -->
    <!-- ********************** -->
    <Application
                 Name="CdmwServices"
                 Host-name="@hostname1val@"
                 Agent-port="-1"
                 App-port="-1">

        <Managed-process
                         Name="Repository"
                         Host-name="@hostname1val@"
                         Type="SERVICE-PROVIDER"
                         Autoended="FALSE"
                         Exec-path="cdmw_naming_and_repository"
                         Args="--CdmwProcessPort=42561 --CdmwLocalisationService=42562 --id=GlobalRepository --conf=cdmw_nar_integ.xml"
                         Port="-1">
            <Init-step Name="initialisation"/>
        </Managed-process>

        <!-- Init graph of processes of this application -->
        <Init-graph>
            <Graph-element Name="Repository"/>

            <Graph-element-root Name="Repository"/>
        </Init-graph>

        <!-- ***************************** -->
        <!--                               -->
        <!-- End of application definition -->
        <!-- ***************************** -->
    </Application>


    <!-- ************************************* -->
    <!-- Application definitions of the system -->
    <!--                                       -->
    <!-- ************************************* -->
    <Application
                 Name="APPL1"
                 Host-name="@hostname1val@"
                 Agent-port="21874"
                 App-port="-1">

        <!-- Default timeouts for processes of the entire system -->
        <Timeout Init="20000" Run="20000" Stop="20000"/>

        <Managed-process
                         Name="P11"
                         Host-name="@hostname1val@"
                         Type="MANAGED-PROCESS"
                         Autoended="FALSE"
                         Exec-path="testftwritesequencing"
                         Args=" --CdmwXMLFile=HelloFaultTolerance2.xml --validateXML --server"
                         Port="-1">
            <Init-step Name="step0"/>
        </Managed-process>
        
        <Managed-process
                         Name="P12"
                         Host-name="@hostname1val@"
                         Type="MANAGED-PROCESS"
                         Autoended="FALSE"
                         Exec-path="testftwritesequencing"
                         Args=" --CdmwXMLFile=HelloFaultTolerance2.xml --validateXML --server --recorder"
                         Port="-1">
            <Init-step Name="step0"/>
        </Managed-process>
        
        <!-- Init graph of processes of this application -->
        <Init-graph>
            <Graph-element Name="P11">
                <Graph-element-successor Name="P12"/>
            </Graph-element>
            <Graph-element Name="P12">
            </Graph-element>
            <Graph-element-root Name="P11"/>
        </Init-graph>

    </Application>


    <Application
                 Name="APPL2"
                 Host-name="@hostname2val@"
                 Agent-port="21875"
                 App-port="-1">

        <!-- Default timeouts for processes of the entire system -->
        <Timeout Init="20000" Run="20000" Stop="20000"/>

        <Managed-process
                         Name="P21"
                         Host-name="@hostname2val@"
                         Type="MANAGED-PROCESS"
                         Autoended="FALSE"
                         Exec-path="testftwritesequencing"
                         Args=" --CdmwXMLFile=HelloFaultTolerance2.xml --validateXML --server"
                         Port="-1">
            <Init-step Name="step0"/>
        </Managed-process>
        
        <!-- Init graph of processes of this application -->
        <Init-graph>
            <Graph-element Name="P21">
            </Graph-element>
            <Graph-element-root Name="P21"/>
        </Init-graph>

    </Application>


    <Application
                 Name="APPL3"
                 Host-name="@hostname3val@"
                 Agent-port="-1"
                 App-port="-1">

        <!-- Default timeouts for processes of the entire system -->
        <Timeout Init="20000" Run="20000" Stop="20000"/>

        <Managed-process
                         Name="P31"
                         Host-name="@hostname3val@"
                         Type="MANAGED-PROCESS"
                         Autoended="FALSE"
                         Exec-path="testftwritesequencing"
                         Args=" --CdmwXMLFile=HelloFaultTolerance2.xml --validateXML --server"
                         Port="-1">
            <Init-step Name="step0"/>
        </Managed-process>
        
        <!-- Init graph of processes of this application -->
        <Init-graph>
            <Graph-element Name="P31">
            </Graph-element>
            <Graph-element-root Name="P31"/>
        </Init-graph>

    </Application>


    <Application
                 Name="APPL4"
                 Host-name="@hostname3val@"
                 Agent-port="21877"
                 App-port="-1">

        <!-- Default timeouts for processes of the entire system -->
        <Timeout Init="20000" Run="20000" Stop="20000"/>

        <Managed-process
                         Name="P31"
                         Host-name="@hostname3val@"
                         Type="MANAGED-PROCESS"
                         Autoended="FALSE"
                         Exec-path="testftwritesequencing"
                         Args=" --CdmwXMLFile=HelloFaultTolerance2.xml --validateXML --server"
                         Port="-1">
            <Init-step Name="step0"/>
        </Managed-process>
        

        <Unmanaged-process
                         Name="P41"
                         Host-name="@hostname1val@"
                         Autoended="TRUE"
                         Exec-path="testftwritesequencing"
                         Args=" --host1=@hostname1val@ --host2=@hostname2val@ --host3=@hostname3val@ --faultmanager=corbaloc::@hostname1val@:4555/fault_manager"/>



        <!-- Init graph of processes of this application -->
        <Init-graph>
            <Graph-element Name="P41">
            </Graph-element>
            <Graph-element-root Name="P41"/>
        </Init-graph>


        <!-- ****************************** -->
        <!--                                -->
        <!-- End of application definitions -->
        <!-- ****************************** -->
    </Application>

    <!-- Init graph of applications of the system-->
    <Init-graph>
        <Graph-element Name="CdmwServices"> 
            <Graph-element-successor Name="APPL1"/>
        </Graph-element>
        <Graph-element Name="APPL4"> 
        </Graph-element>
        <Graph-element Name="APPL1"> 
            <Graph-element-successor Name="APPL2"/>
        </Graph-element>
        <Graph-element Name="APPL2"> 
            <Graph-element-successor Name="APPL3"/>
        </Graph-element>
        <Graph-element Name="APPL3"> 
            <Graph-element-successor Name="APPL4"/>
        </Graph-element>
        <Graph-element Name="APPL4"> 
        </Graph-element>
        <Graph-element-root Name="CdmwServices"/>
    </Init-graph>

    
    <!-- ************************ -->
    <!--                          -->
    <!-- End of system definition -->
    <!-- ************************ -->
</System>

=== jmnb-sdbg-edi/cardamom/tags/CARDAMOM_V2_1_CE/SystemMngt/valid/validationdata/data/V-SMG-022-1.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- ===================================================================== -->
<!--
 * This file is part of CARDAMOM (R) which is jointly developed by THALES
 * and SELEX-SI. It is derivative work based on PERCO Copyright (C) THALES
 * 2000-2003. All rights reserved.
 * 
 * Copyright (C) THALES 2004-2005. All rights reserved
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Library General Public License as published
 * by the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Library General Public
 * License along with CARDAMOM; see the file COPYING. If not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
-->
<!-- ===================================================================== -->


<!DOCTYPE System SYSTEM "CdmwPlatformMngtSystem.dtd">

<!-- ***************** -->
<!-- System definition -->
<!--                   -->
<!-- ***************** -->
<System Name="validation" Port="21869">

    <!-- Default timeouts for processes of the entire system -->
    <Timeout Init="20000" Run="20000" Stop="20000"/>

    <!-- Default monitorings for the entire system -->
    <Host-monitoring Pull-interval="10000" Pull-timeout="3000"/>
    <App-monitoring  Pull-interval="0" Pull-timeout="0"/>
    <Proc-monitoring Model="NO_MONITORING"
                     Pull-interval="0" Pull-timeout="0"
                     Push-interval="0" Push-timeout="0"/>

    <!-- Services of the system -->
    <Service Name="NamingAndRepositoryService"
             App-name="CdmwServices"
             Process-name="Repository"/>


    <!-- Hosts of the system -->
    <Host Name="@hostname1val@"
          App-exec-path="cdmw_platform_application"
          Agent-exec-path="cdmw_platform_agent"/>
    <Host Name="@hostname2val@"
          App-exec-path="cdmw_platform_application"
          Agent-exec-path="cdmw_platform_agent"/>
    <Host Name="@hostname3val@"
          App-exec-path="cdmw_platform_application"
          Agent-exec-path="cdmw_platform_agent"/>

    <!-- ********************** -->
    <!-- Application definition -->
    <!--                        -->
    <!-- ********************** -->
    <Application
                 Name="CdmwServices"
                 Host-name="@hostname1val@"
                 Agent-port="-1"
                 App-port="-1">

        <Managed-process
                         Name="Repository"
                         Host-name="@hostname1val@"
                         Type="SERVICE-PROVIDER"
                         Autoended="FALSE"
                         Exec-path="cdmw_naming_and_repository"
                         Args="--CdmwProcessPort=42561 --CdmwLocalisationService=42562 --id=GlobalRepository --conf=cdmw_nar_integ.xml"
                         Port="-1">
            <Init-step Name="initialisation"/>
        </Managed-process>

        <!-- Init graph of processes of this application -->
        <Init-graph>
            <Graph-element Name="Repository"/>

            <Graph-element-root Name="Repository"/>
        </Init-graph>

        <!-- ***************************** -->
        <!--                               -->
        <!-- End of application definition -->
        <!-- ***************************** -->
    </Application>


    <!-- ************************************* -->
    <!-- Application definitions of the system -->
    <!--                                       -->
    <!-- ************************************* -->
    <Application
                 Name="APPL1"
                 Host-name="@hostname2val@"
                 Agent-port="21874"
                 App-port="-1">

        <!-- Default timeouts for processes of the entire system -->
        <Timeout Init="20000" Run="20000" Stop="20000"/>

        <Managed-process
                         Name="observer"
                         Host-name="@hostname2val@"
                         Type="MANAGED-PROCESS"
                         Autoended="FALSE"
                         Exec-path="cdmw_perf_daemon"
                         Args=" --CdmwXMLFile=V-SMG-022-data/TestPerfDaemon.xml --validateXML --observer --nb-test=100 --limit-time=150 --in-percent-case=95 --supervision=corbaloc::@hostname1val@:21871/CdmwPlatformMngtSupervision"
                         Port="-1">
            <Init-step Name="step0"/>
        </Managed-process>

		<Init-graph>
		    <Graph-element Name="observer"/>
			<Graph-element-root Name="observer"/>
    	</Init-graph>
   </Application>


    <Application
                 Name="APPL2"
                 Host-name="@hostname3val@"
                 Agent-port="21875"
                 App-port="-1">

        <!-- Default timeouts for processes of the entire system -->
        <Timeout Init="20000" Run="20000" Stop="20000"/>

        <Managed-process
                         Name="killer"
                         Host-name="@hostname3val@"
                         Type="MANAGED-PROCESS"
                         Autoended="TRUE"
                         Exec-path="cdmw_killer.sh"
                         Args=" --CdmwXMLFile=V-SMG-022-data/TestPerfDaemon.xml --validateXML"
                         Port="-1">
            <Init-step Name="step0"/>
        </Managed-process>              
		<Init-graph>
		    <Graph-element Name="killer"/>
			<Graph-element-root Name="killer"/>
    	</Init-graph>    
    </Application>


    <!-- Init graph of applications of the system-->
    <Init-graph>
        <Graph-element Name="CdmwServices"> 
            <Graph-element-successor Name="APPL1"/>
        </Graph-element>
         <Graph-element Name="APPL1"> 
            <Graph-element-successor Name="APPL2"/>
        </Graph-element>
        <Graph-element-root Name="CdmwServices"/>
    </Init-graph>

    
    <!-- ************************ -->
    <!--                          -->
    <!-- End of system definition -->
    <!-- ************************ -->
</System>

=== jmnb-sdbg-edi/cardamom/ProdTests/qualif/common/data/Q-006-err10.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
 * =========================================================================== *
 * This file is part of CARDAMOM (R) which is jointly developed by THALES
 * and SELEX-SI.
 * 
 * It is derivative work based on PERCO Copyright (C) THALES 2000-2003.
 * All rights reserved.
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Library General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your
 * option) any later version.
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Library General
 * Public License along with CARDAMOM; see the file COPYING. If not, write to
 * the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 * =========================================================================== *
-->


<!DOCTYPE System SYSTEM "CdmwPlatformMngtSystem.dtd">

<!-- ***************** -->
<!-- System definition -->
<!--                   -->
<!-- ***************** -->
<System Name="S1" Port="21869">

    <!-- Default timeouts for processes of the entire system -->
	<Timeout Init="20000" Run="20000" Stop="20000"/>

    <!-- Default monitorings for the entire system -->
	<Host-monitoring Pull-interval="1000" Pull-timeout="1500"/>
	<App-monitoring  Pull-interval="1000" Pull-timeout="1000"/>
    <Proc-monitoring Model="NO_MONITORING"
                     Pull-interval="0" Pull-timeout="0"
                     Push-interval="0" Push-timeout="0"/>

    <!-- Run sets of the system -->
    <Run-set Name="R1">
        <Run-set-element Name="A1"/>
        <Run-set-element Name="A2"/>
        <Run-set-element Name="A2"/>
    </Run-set>

<!-- ************************ -->
<!--                          -->
<!-- End of system definition -->
<!-- ************************ -->
</System>
