=== jmnb-sdbg-edi/cardamom/tags/start/SystemMngt/platformadmin/c++/data/CdmwPlatformMngtSystem.dtd
<!-- ===================================================================== -->
<!--
 * This file is part of CARDAMOM (R) which is jointly developed by THALES 
 * and SELEX-SI. 
 * 
 * It is derivative work based on PERCO Copyright (C) THALES 2000-2003. 
 * All rights reserved.
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it under 
 * the terms of the GNU Library General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your 
 * option) any later version. 
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT 
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public 
 * License for more details. 
 * 
 * You should have received a copy of the GNU Library General 
 * Public License along with CARDAMOM; see the file COPYING. If not, write to 
 * the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
-->
<!-- ===================================================================== -->

<!-- Perco deployment file DTD (Thales ISR ) -->

<!-- ***************** -->
<!-- System definition -->
<!-- ***************** -->
<!ELEMENT System (
    Timeout,
    Host-monitoring,
    App-monitoring,
    Proc-monitoring,
    Service*,
    Entity*,
    Property*,
    Host*,
    Application*,
    Init-graph?,
    Stop-graph?,
    Run-set* )>
<!ATTLIST System
    Name CDATA #REQUIRED
	Port CDATA #REQUIRED
>

<!-- ******************************** -->
<!-- Timeout definition for processes -->
<!-- ******************************** -->
<!ELEMENT Timeout EMPTY>
<!ATTLIST Timeout
	Init CDATA #REQUIRED
	Run  CDATA #REQUIRED
	Stop CDATA #REQUIRED
>

<!-- ************************** -->
<!-- Host monitoring definition -->
<!-- ************************** -->
<!ELEMENT Host-monitoring EMPTY>
<!ATTLIST Host-monitoring
    Pull-interval CDATA #REQUIRED
    Pull-timeout  CDATA #REQUIRED
>

<!-- ********************************* -->
<!-- Application monitoring definition -->
<!-- ********************************* -->
<!ELEMENT App-monitoring EMPTY>
<!ATTLIST App-monitoring
    Pull-interval CDATA #REQUIRED
    Pull-timeout  CDATA #REQUIRED
>

<!-- ***************************** -->
<!-- Process monitoring definition -->
<!-- ***************************** -->
<!ELEMENT Proc-monitoring EMPTY>
<!ATTLIST Proc-monitoring
    Model ( NO_MONITORING |
            PULL_MONITORING_MODEL |
            PUSH_MONITORING_MODEL |
            FULL_MONITORING_MODEL )
            #REQUIRED
    Pull-interval CDATA #REQUIRED
    Pull-timeout  CDATA #REQUIRED
    Push-interval CDATA #REQUIRED
    Push-timeout  CDATA #REQUIRED
>

<!-- ****************** -->
<!-- Service definition -->
<!-- ****************** -->
<!ELEMENT Service EMPTY>
<!ATTLIST Service
	Name         CDATA #REQUIRED
	App-name     CDATA #REQUIRED
	Process-name CDATA #REQUIRED
>

<!-- ***************** -->
<!-- Entity definition -->
<!-- ***************** -->
<!ELEMENT Entity EMPTY>
<!ATTLIST Entity
	Name CDATA #REQUIRED
>

<!-- ******************* -->
<!-- Property definition -->
<!-- ******************* -->
<!ELEMENT Property EMPTY>
<!ATTLIST Property
	Name CDATA #REQUIRED
>

<!-- *************** -->
<!-- Host definition -->
<!-- *************** -->
<!ELEMENT Host (
    Host-monitoring?,
    Property* )>
<!ATTLIST Host
	Name            CDATA #REQUIRED
	App-exec-path   CDATA #REQUIRED
	Agent-exec-path CDATA #REQUIRED
	Probe-exec-path CDATA #REQUIRED
    Probe-port      CDATA #IMPLIED
    Probe-args      CDATA #IMPLIED
    Probe-run-dir   CDATA #IMPLIED
>

<!-- ********************** -->
<!-- Application definition -->
<!-- ********************** -->
<!ELEMENT Application (
    Timeout?,
    App-monitoring?,
    Proc-monitoring?,
    Service*,
    Entity*,
    Property*,
    ( Managed-process | Unmanaged-process )*,
    Init-graph?,
    Stop-graph? )>
<!ATTLIST Application
	Name          CDATA #REQUIRED
    Host-name     CDATA #REQUIRED
    Agent-port    CDATA #IMPLIED
    Agent-args    CDATA #IMPLIED
    Agent-run-dir CDATA #IMPLIED
    App-port      CDATA #IMPLIED
    App-args      CDATA #IMPLIED
    App-run-dir   CDATA #IMPLIED
>

<!-- ************************** -->
<!-- Managed process definition -->
<!-- ************************** -->
<!ELEMENT Managed-process (
    Init-step+,
    Run-timeout?,
    Stop-timeout?,
    Proc-monitoring?,
    Service*,
    Entity*,
    Property*,
    Activity-point* )>
<!ATTLIST Managed-process
	Name      CDATA #REQUIRED
	Host-name CDATA #REQUIRED
	Type      ( MANAGED-PROCESS |
                SERVICE-PROVIDER |
                COMPONENT-SERVER )
                #REQUIRED
	Autoended ( FALSE | TRUE ) #REQUIRED
	Exec-path CDATA #REQUIRED
    Port      CDATA #IMPLIED
	Args      CDATA #IMPLIED
	Run-dir   CDATA #IMPLIED
>

<!-- ******************** -->
<!-- Init step definition -->
<!-- ******************** -->
<!ELEMENT Init-step EMPTY>
<!ATTLIST Init-step
	Name    CDATA #REQUIRED
    Timeout CDATA #IMPLIED
>

<!-- ********************** -->
<!-- Run timeout definition -->
<!-- ********************** -->
<!ELEMENT Run-timeout EMPTY>
<!ATTLIST Run-timeout
    Timeout CDATA #REQUIRED
>

<!-- *********************** -->
<!-- Stop timeout definition -->
<!-- *********************** -->
<!ELEMENT Stop-timeout EMPTY>
<!ATTLIST Stop-timeout
    Timeout CDATA #REQUIRED
>

<!-- ************************* -->
<!-- Activity point definition -->
<!-- ************************* -->
<!ELEMENT Activity-point EMPTY>
<!ATTLIST Activity-point
    Name                CDATA #REQUIRED
    Monitoring-interval CDATA #REQUIRED
    Monitoring-timeout  CDATA #REQUIRED
>

<!-- *************************** -->
<!-- Unamaged process definition -->
<!-- *************************** -->
<!ELEMENT Unmanaged-process (
    Property* )>
<!ATTLIST Unmanaged-process
	Name      CDATA #REQUIRED
	Host-name CDATA #REQUIRED
	Autoended ( FALSE | TRUE ) #REQUIRED
	Exec-path CDATA #REQUIRED
    Port      CDATA #IMPLIED
	Args      CDATA #IMPLIED
	Run-dir   CDATA #IMPLIED
>

<!-- *************************** -->
<!-- Dependency graph definition -->
<!-- *************************** -->
<!ELEMENT Init-graph (
    Graph-element+,
    Graph-element-root+ )>
    
<!ELEMENT Stop-graph (
    Graph-element+,
    Graph-element-root+ )>
    
<!ELEMENT Graph-element (
    Graph-element-successor* )>
<!ATTLIST Graph-element
	Name CDATA #REQUIRED
	Step CDATA #IMPLIED
>

<!ELEMENT Graph-element-successor EMPTY>
<!ATTLIST Graph-element-successor
	Name CDATA #REQUIRED
	Step CDATA #IMPLIED
>

<!ELEMENT Graph-element-root EMPTY>
<!ATTLIST Graph-element-root
	Name CDATA #REQUIRED
	Step CDATA #IMPLIED
>

<!-- ****************** -->
<!-- Run set definition -->
<!-- ****************** -->
<!ELEMENT Run-set (
    Run-set-element+ )>
<!ATTLIST Run-set
	Name CDATA #REQUIRED
>
<!ELEMENT Run-set-element EMPTY>
<!ATTLIST Run-set-element
    Name CDATA #REQUIRED
>

<!-- ******************************* -->
<!-- Additional definitions used for -->
<!-- hot process modification        -->
<!-- ******************************* -->
<!ELEMENT Life-cycle (
    Init-step+,
    Run-timeout,
    Stop-timeout )>

=== jmnb-sdbg-edi/cardamom/tags/CARDAMOM_V2_1_CE/ProdTests/qualif/common/data/Q-120.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
 * =========================================================================== *
 * THALES (R) - CARDAMOM
 *
 * Copyright (c) THALES 2000-2004 All rights reserved
 * This file and the information  it contains  are   property  of  THALES  and
 * confidential.   They  shall  not be reproduced nor disclosed  to any person
 * except to those having  a need  to know them without  prior written consent
 * of THALES.
 * =========================================================================== *
-->


<!DOCTYPE System SYSTEM "./CdmwPlatformMngtSystem.dtd">

<!-- ***************** -->
<!-- System definition -->
<!--                   -->
<!-- ***************** -->

<System Name="MySystem" Port="21869">

	<!-- Default timeouts for processes of the entire system -->
	<Timeout Init="20000" Run="20000" Stop="20000"/>
	<!-- Default monitorings for the entire system -->
	<Host-monitoring Pull-interval="1000" Pull-timeout="1500"/>
	<App-monitoring Pull-interval="060" Pull-timeout="070"/>
	<Proc-monitoring Model="NO_MONITORING" 
	                 Pull-interval="021" Pull-timeout="031" 
	                 Push-interval="041" Push-timeout="051"/>
	
	<!-- Services of the system -->
	<!-- <Service Name="NamingAndRepositoryService" 
	         App-name="CardamomServices" 
	         Process-name="Repository"/>  -->
            <!--	     
	      App-exec-path="/home/florenna/MINICARDAMOM_DEVELOP/CARDAMOM_INSTALLED/bin/cdmw_platform_application" 
	      Agent-exec-path="/home/florenna/MINICARDAMOM_DEVELOP/CARDAMOM_INSTALLED/bin/cdmw_platform_agent" 
	      Probe-exec-path="/home/florenna/MINICARDAMOM_DEVELOP/CARDAMOM_INSTALLED/bin/cdmw_host_probe">
	      -->
	
	<!-- Hosts of the system -->
	<Host Name="@hostname1val@"  >
		<Host-monitoring Pull-interval="2000" Pull-timeout="2500"/>
	</Host>

	<Host Name="@hostname2val@"  >
		<Host-monitoring Pull-interval="2000" Pull-timeout="2500"/>
	</Host>
	
	<!-- ********************** -->
	<!-- Application definition -->
	<!--                        -->
	<!-- ********************** -->
	<Application Name="HELLO_WORLD1" 
	             Host-name="@hostname1val@" 
	             Agent-port="-1" 
	             App-port="-1">
	             
		<!-- Default timeouts for processes of this application -->
		<Timeout Init="20000" Run="20000" Stop="20000"/>
		
		<!-- Monitoring of this application -->
		<App-monitoring Pull-interval="021" Pull-timeout="031"/>
		
		<!-- ******************* -->
		<!-- Process definitions -->
		<!--                     -->
		<!-- ******************* -->
               <Unmanaged-process Name="HelloProcess1"
                     Host-name="@hostname1val@" 
                     Autoended="TRUE" 
                     Exec-path="./proc1.csh"
		     Port="-1" />
		     

               <Unmanaged-process Name="HelloProcess2"
                     Host-name="@hostname2val@" 
                     Autoended="TRUE" 
                     Exec-path="/home/florenna/proc2.csh"
		     Port="-1" />
		    

		
		<!-- ************************** -->
		<!--                            -->
		<!-- End of process definitions -->
		<!-- ************************** -->
		
		<!-- Init graph of processes of this application -->
		<Init-graph>
		    <Graph-element Name="HelloProcess1">
			</Graph-element> 

			<Graph-element-root Name="HelloProcess1"/>
		</Init-graph>
		
		<!-- ***************************** -->
		<!--                               -->
		<!-- End of application definition -->
		<!-- ***************************** -->
	</Application>
	
	<!-- ********************** -->
	<!-- Application definition -->
	<!-- HELLO_WORLD2                       -->
	<!-- ********************** -->
	<Application Name="HELLO_WORLD2" 
	             Host-name="@hostname1val@" 
	             Agent-port="-1" 
	             App-port="-1">
	             
		<!-- Default timeouts for processes of this application -->
		<Timeout Init="20000" Run="20000" Stop="20000"/>
		
		<!-- Monitoring of this application -->
		<App-monitoring Pull-interval="021" Pull-timeout="031"/>
		
		<!-- ******************* -->
		<!-- Process definitions -->
		<!--                     -->
		<!-- ******************* -->
               <Unmanaged-process Name="HelloProcess1_hello2"
                     Host-name="@hostname1val@" 
                     Autoended="TRUE" 
                     Exec-path="./proc1.csh"
		     Port="-1" />
		     

		
		<!-- ************************** -->
		<!--                            -->
		<!-- End of process definitions -->
		<!-- ************************** -->
		
		<!-- Init graph of processes of this application -->
		<Init-graph>
		    <Graph-element Name="HelloProcess1_hello2">

			</Graph-element>  

			<Graph-element-root Name="HelloProcess1_hello2"/>
		</Init-graph>
		
		<!-- ***************************** -->
		<!--                               -->
		<!-- End of application definition -->
		<!-- ***************************** -->
	</Application>


	<!-- ********************** -->
	<!-- Application definition -->
	<!-- HELLO_WORLD3                       -->
	<!-- ********************** -->
	<Application Name="HELLO_WORLD3" 
	             Host-name="@hostname1val@" 
	             Agent-port="-1" 
	             App-port="-1">
	             
		<!-- Default timeouts for processes of this application -->
		<Timeout Init="20000" Run="20000" Stop="20000"/>
		
		<!-- Monitoring of this application -->
		<App-monitoring Pull-interval="021" Pull-timeout="031"/>
		
		<!-- ******************* -->
		<!-- Process definitions -->
		<!--                     -->
		<!-- ******************* -->
               <Unmanaged-process Name="HelloProcess1_hello3"
                     Host-name="@hostname1val@" 
                     Autoended="TRUE" 
                     Exec-path="./proc1.csh"
		     Port="-1" />
		     

		
		<!-- ************************** -->
		<!--                            -->
		<!-- End of process definitions -->
		<!-- ************************** -->
		
		<!-- Init graph of processes of this application -->
		<Init-graph>
		    <Graph-element Name="HelloProcess1_hello3">

			</Graph-element> 

			<Graph-element-root Name="HelloProcess1_hello3"/>
		</Init-graph>
		
		<!-- ***************************** -->
		<!--                               -->
		<!-- End of application definition -->
		<!-- ***************************** -->
	</Application>

	
	<Application Name="HELLO_WORLD4" 
	             Host-name="@hostname1val@" 
	             Agent-port="-1" 
	             App-port="-1">
	             
		<!-- Default timeouts for processes of this application -->
		<Timeout Init="20000" Run="20000" Stop="20000"/>
		
		<!-- Monitoring of this application -->
		<App-monitoring Pull-interval="021" Pull-timeout="031"/>
		
		<!-- ******************* -->
		<!-- Process definitions -->
		<!--                     -->
		<!-- ******************* -->
		    
	       <!-- the unmanaged test process to start -->
               <Unmanaged-process Name="HelloProcess1_hello4"
                     Host-name="@hostname1val@" 
                     Autoended="TRUE" 
                     Exec-path="cdmw_testvalidnavigability"
		     Port="-1" />

		
		<!-- ************************** -->
		<!--                            -->
		<!-- End of process definitions -->
		<!-- ************************** -->
		
		<!-- Init graph of processes of this application -->
		<Init-graph>
		    <Graph-element Name="HelloProcess1_hello4">
			</Graph-element> 

			<Graph-element-root Name="HelloProcess1_hello4"/>
		</Init-graph>
		
		<!-- ***************************** -->
		<!--                               -->
		<!-- End of application definition -->
		<!-- ***************************** -->
	</Application>

	<!-- Stop graph of applications of the system-->
	
	<Init-graph>
		    <Graph-element Name="HELLO_WORLD4">
			</Graph-element> 
			<Graph-element-root Name="HELLO_WORLD4"/>
	</Init-graph>
	
	<Stop-graph>
		<Graph-element Name="HELLO_WORLD4">
		</Graph-element>
		<Graph-element-root Name="HELLO_WORLD4"/>
	</Stop-graph> 

<!-- Run sets of the system -->
<!--
<Run-set Name="RS1">
  <Run-set-element Name="HelloProcess1"/>
  <Run-set-element Name="HelloProcess2"/>
  <Run-set-element Name="HelloProcess3"/>
</Run-set>
-->
	
	
</System>

<!-- ************************ -->
<!--                          -->
<!-- End of system definition -->
<!-- ************************ -->

=== jmnb-sdbg-edi/cardamom/XMLServer/valid/validationdata/data/V-XMS-001-1.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- ===================================================================== -->
<!--
 * This file is part of CARDAMOM (R) which is jointly developed by THALES
 * and SELEX-SI. It is derivative work based on PERCO Copyright (C) THALES
 * 2000-2003. All rights reserved.
 * 
 * Copyright (C) THALES 2004-2005. All rights reserved
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Library General Public License as published
 * by the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Library General Public
 * License along with CARDAMOM; see the file COPYING. If not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
-->
<!-- ===================================================================== -->

<!--Cdmw deployment file for validation test:-->
<!--Cdmw Repository launched with traces enabled-->
<!--...-->
<!--...-->
<!DOCTYPE System SYSTEM "CdmwPlatformMngtSystem.dtd">

<!-- ***************** -->
<!-- System definition -->
<!--                   -->
<!-- ***************** -->
<System Name="system_deployment" Port="21869">

    <!-- Default timeouts for processes of the entire system -->
    <Timeout Init="30000" Run="10000" Stop="10000"/>

    <!-- Default monitorings for the entire system -->
    <Host-monitoring Pull-interval="1000" Pull-timeout="1500"/>
    <App-monitoring  Pull-interval="060" Pull-timeout="070"/>
    <Proc-monitoring Model="NO_MONITORING"
                     Pull-interval="021" Pull-timeout="031"
                     Push-interval="041" Push-timeout="051"/>

    <!-- Services of the system -->
    <Service Name="NamingAndRepositoryService"
             App-name="CdmwServices"
             Process-name="Repository"/>

    <Service Name="XMLService"
             App-name="CdmwServices"
             Process-name="XML"/>

    <!-- Hosts of the system -->
    <Host Name="@hostname1val@"
          App-exec-path="cdmw_platform_application"
          Agent-exec-path="cdmw_platform_agent"/>

    <Host Name="@hostname2val@"
          App-exec-path="cdmw_platform_application"
          Agent-exec-path="cdmw_platform_agent"/>

    <!-- ********************** -->
    <!-- Application definition -->
    <!--                        -->
    <!-- ********************** -->
    <Application Name="CdmwServices"
                 Host-name="@hostname1val@"
                 Agent-port="-1"
                 App-port="-1">

        <!-- Default timeouts for processes of this application 
        <Timeout Init="20000" Run="20000" Stop="20000"/>
        -->

        <!-- Monitoring of this application -->
        <App-monitoring Pull-interval="021" Pull-timeout="031"/>


        <!-- ******************* -->
        <!-- Process definitions -->
        <!--                     -->
        <!-- ******************* -->
        <Managed-process Name="Repository"
                         Host-name="@hostname1val@"
                         Type="SERVICE-PROVIDER"
                         Autoended="FALSE"
                         Exec-path="cdmw_naming_and_repository" 
                         Args="--id=GlobalRepository --conf=cdmw_nar_integ_xms.xml --trace" 
                         Port="22456">
            <Init-step Name="initialisation" Timeout="30000"/>
        <!--    <Run-timeout Timeout="10000"/>
            <Stop-timeout Timeout="10000"/>  -->
        </Managed-process>

        <Managed-process Name="XML"
                         Host-name="@hostname1val@"
                         Type="SERVICE-PROVIDER"
                         Autoended="FALSE"
                         Exec-path="cdmw_xml_server.sh"
                         Args="--doctypedir=. --validate"
                         Port="-1">
            <Init-step Name="initialisation" Timeout="30000"/>
        <!--    <Run-timeout Timeout="1000"/>
            <Stop-timeout Timeout="2000"/> -->
        </Managed-process>
        
        <Init-graph>
            <Graph-element Name="Repository">
                <Graph-element-successor Name="XML"/>
            </Graph-element>
            
            <Graph-element Name="XML"/>
                        
            <Graph-element-root Name="Repository"/>
        </Init-graph>
 
        <Stop-graph>
            <Graph-element Name="XML">
                <Graph-element-successor Name="Repository"/>
            </Graph-element>
            <Graph-element Name="Repository"/>

            <Graph-element-root Name="XML"/>
        </Stop-graph>
        
    </Application>

    <Application Name="XMLValidation"
                 Host-name="@hostname2val@"
                 Agent-port="-1"
                 App-port="-1">

        <!-- Default timeouts for processes of this application -->
       <!-- <Timeout Init="20000" Run="20000" Stop="20000"/> -->

        <!-- Monitoring of this application -->
        <App-monitoring Pull-interval="021" Pull-timeout="031"/> 

        <Managed-process Name="TestClient"
                         Host-name="@hostname2val@"
                         Type="MANAGED-PROCESS"
                         Autoended="FALSE"
                         Exec-path="xml_service_test_client.sh"
                         Port="24010"
                         Args="">
            <Init-step Name="initialisation" Timeout="30000"/>
        <!--    <Run-timeout Timeout="1000"/>
            <Stop-timeout Timeout="2000"/> -->
        </Managed-process>
                          
        <Init-graph>
            <Graph-element Name="TestClient"/>
            <Graph-element-root Name="TestClient"/>
        </Init-graph>
        
        <Stop-graph>
            <Graph-element Name="TestClient"/>
            <Graph-element-root Name="TestClient"/>
        </Stop-graph>

    </Application>

    <!-- ****************************** -->
    <!--                                -->
    <!-- End of application definitions -->
    <!-- ****************************** -->

    <!-- Init graph of applications of the system-->
    <Init-graph>
        <Graph-element Name="CdmwServices"> 
            <Graph-element-successor Name="XMLValidation"/>
        </Graph-element>
        
        <Graph-element Name="XMLValidation"/> 

        <Graph-element-root Name="CdmwServices"/> 
    </Init-graph>

<!-- ************************ -->
<!--                          -->
<!-- End of system definition -->
<!-- ************************ -->
</System>

=== jmnb-sdbg-edi/cardamom/tags/CARDAMOM_V2_1_CE/Time/valid/validationdata/data/V-TMG-004-1.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- ===================================================================== -->
<!--
 * This file is part of CARDAMOM (R) which is jointly developed by THALES
 * and SELEX-SI. All rights reserved.
 * 
 * Copyright (C) SELEX-SI 2004-2005. All rights reserved
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Library General Public License as published
 * by the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Library General Public
 * License along with CARDAMOM; see the file COPYING. If not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
-->
<!-- ===================================================================== -->

<!DOCTYPE System SYSTEM "CdmwPlatformMngtSystem.dtd">

<!-- ***************** -->
<!-- System definition -->
<!--                   -->
<!-- ***************** -->
<System Name="integ_local" Port="21869">

    <!-- Default timeouts for processes of the entire system -->
	<Timeout Init="20000" Run="20000" Stop="20000"/>

    <!-- Default monitorings for the entire system -->
	<Host-monitoring Pull-interval="10000" Pull-timeout="3000"/>
	<App-monitoring  Pull-interval="0" Pull-timeout="0"/>
    <Proc-monitoring Model="NO_MONITORING"
                     Pull-interval="0" Pull-timeout="0"
                     Push-interval="0" Push-timeout="0"/>

    <!-- Services of the system -->
	<Service Name="NamingAndRepositoryService"
             App-name="CdmwServices"
             Process-name="Repository"/>

    <!-- Hosts of the system -->
	<Host
        Name="@hostname1val@"
        App-exec-path="cdmw_platform_application"
        Agent-exec-path="cdmw_platform_agent"/>

	<Host
        Name="@hostname2val@"
        App-exec-path="cdmw_platform_application"
        Agent-exec-path="cdmw_platform_agent"/>

    <!-- ********************** -->
    <!-- Application definition -->
    <!--                        -->
    <!-- ********************** -->
	<Application
        Name="CdmwServices"
        Host-name="@hostname1val@"
        Agent-port="-1"
        App-port="-1">

	<Managed-process
            Name="Repository"
            Host-name="@hostname1val@"
            Type="SERVICE-PROVIDER"
            Autoended="FALSE"
            Exec-path="cdmw_naming_and_repository"
            Args="--CdmwProcessPort=42561 --CdmwLocalisationService=42667 --id=GlobalRepository --conf=cdmw_nar_integ_clock.xml"
            Port="-1">
		<Init-step Name="initialisation"/>
	</Managed-process>

        <!-- Init graph of processes of this application -->
        <Init-graph>
            <Graph-element Name="Repository"/>

            <Graph-element-root Name="Repository"/>
        </Init-graph>

    <!-- ***************************** -->
    <!--                               -->
    <!-- End of application definition -->
    <!-- ***************************** -->
	</Application>

    <!-- ************************************* -->
    <!-- Application definitions of the system -->
    <!--                                       -->
    <!-- ************************************* -->
	<Application
        Name="FTApplication"
        Host-name="@hostname1val@"
        Agent-port="-1"
        App-port="-1">

        <!-- Default timeouts for processes of the entire system -->
        <Timeout Init="50000" Run="50000" Stop="50000"/>

		<Managed-process
            Name="FTClock1"
            Host-name="@hostname1val@"
            Type="MANAGED-PROCESS"
            Autoended="FALSE"
            Exec-path="ftclocksvcs"
            Args="--CdmwXMLFile=FTClock.xml --validateXML --PointToPoint --SetPrimary"
            Port="-1">
            <Init-step Name="step0"/>
		</Managed-process>
                         
        <Managed-process
            Name="FTClock2"
            Host-name="@hostname2val@"
            Type="MANAGED-PROCESS"
            Autoended="FALSE"
            Exec-path="ftclocksvcs"
            Args="--CdmwXMLFile=FTClock.xml --validateXML --PointToPoint"
            Port="-1">
            <Init-step Name="step0"/>
		</Managed-process>

        <Managed-process
            Name="FTClock3"
            Host-name="@hostname2val@"
            Type="MANAGED-PROCESS"
            Autoended="FALSE"
            Exec-path="ftclocksvcs"
            Args="--CdmwXMLFile=FTClock.xml --validateXML --PointToPoint"
            Port="-1">
            <Init-step Name="step0"/>
		</Managed-process>

		<Managed-process
            Name="group_creator"
            Host-name="@hostname1val@"
            Type="MANAGED-PROCESS"
            Autoended="TRUE"
            Exec-path="ftclockcommon"
            Args="--host1=@hostname1val@ --host2=@hostname2val@ --host3=@hostname3val@ --proc1=FTClock1 --proc2=FTClock2 --proc3=FTClock3 --CdmwXMLFile=GroupCreator.xml --validateXML --PointToPoint "
            Port="-1">
            <Init-step Name="step0"/>
		</Managed-process>
                         
		<Managed-process
            Name="client"
            Host-name="@hostname1val@"
            Type="MANAGED-PROCESS"
            Autoended="TRUE"
            Exec-path="ftclockclienttest"
            Args="--CdmwXMLFile=ClientClock.xml --validateXML"
            Port="-1">
            <Init-step Name="step0"/>
		</Managed-process>
                         
        <!-- Init graph of processes of this application -->
        <Init-graph>
			<Graph-element Name="group_creator">
			    <Graph-element-successor Name="FTClock1"/>
			    <Graph-element-successor Name="FTClock2"/>
			    <Graph-element-successor Name="FTClock3"/>
            </Graph-element>

   		    <Graph-element Name="FTClock1">
			    <Graph-element-successor Name="client"/>
            </Graph-element>

   		    <Graph-element Name="FTClock2">
			    <Graph-element-successor Name="client"/>
            </Graph-element>

   		    <Graph-element Name="FTClock3">
			    <Graph-element-successor Name="client"/>
            </Graph-element>

   		    <Graph-element Name="client"/>
            
            <Graph-element-root Name="group_creator"/>
 	</Init-graph>

    <!-- ****************************** -->
    <!--                                -->
    <!-- End of application definitions -->
    <!-- ****************************** -->
	</Application>

    <!-- Init graph of applications of the system-->
    <Init-graph>
        <Graph-element Name="CdmwServices"> 
            <Graph-element-successor Name="FTApplication"/>
        </Graph-element>

        <Graph-element-root Name="CdmwServices"/>
    </Init-graph>

<!-- ************************ -->
<!--                          -->
<!-- End of system definition -->
<!-- ************************ -->
</System>
