=== jmnb-sdbg-edi/cardamom/SystemMngt/platformftsystem/c++/data/CdmwSystemMngtDatastore_Desc.dtd
<!-- ===================================================================== -->
<!--
 * This file is part of CARDAMOM (R) which is jointly developed by THALES
 * and SELEX-SI. It is derivative work based on PERCO Copyright (C) THALES
 * 2000-2003. All rights reserved.
 * 
 * Copyright (C) THALES 2004-2005. All rights reserved
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Library General Public License as published
 * by the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Library General Public
 * License along with CARDAMOM; see the file COPYING. If not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
-->
<!-- ===================================================================== -->

<!--
* =========================================================================== *
* This code has been generated by CDMW Code Generator 1.0
* on Fri Mar 11 13:23:25 CET 2005
* DO NOT EDIT !!!
* =========================================================================== *
-->

<!ELEMENT process (services+)>

<!ELEMENT services (fault-tolerance)>

<!ELEMENT ManagedElementDataStore.datastore EMPTY>
<!ATTLIST ManagedElementDataStore.datastore
   datastore-id CDATA #REQUIRED 
   chunk-size CDATA #IMPLIED
   freeze-size CDATA #IMPLIED
   freeze-timeout CDATA #IMPLIED
>
<!ELEMENT SystemDataStore.datastore EMPTY>
<!ATTLIST SystemDataStore.datastore
   datastore-id CDATA #REQUIRED 
   chunk-size CDATA #IMPLIED
   freeze-size CDATA #IMPLIED
   freeze-timeout CDATA #IMPLIED
>
<!ELEMENT HostDataStore.datastore EMPTY>
<!ATTLIST HostDataStore.datastore
   datastore-id CDATA #REQUIRED 
   chunk-size CDATA #IMPLIED
   freeze-size CDATA #IMPLIED
   freeze-timeout CDATA #IMPLIED
>
<!ELEMENT ApplicationDataStore.datastore EMPTY>
<!ATTLIST ApplicationDataStore.datastore
   datastore-id CDATA #REQUIRED 
   chunk-size CDATA #IMPLIED
   freeze-size CDATA #IMPLIED
   freeze-timeout CDATA #IMPLIED
>
<!ELEMENT ProcessDataStore.datastore EMPTY>
<!ATTLIST ProcessDataStore.datastore
   datastore-id CDATA #REQUIRED 
   chunk-size CDATA #IMPLIED
   freeze-size CDATA #IMPLIED
   freeze-timeout CDATA #IMPLIED
>
<!ELEMENT EntityDataStore.datastore EMPTY>
<!ATTLIST EntityDataStore.datastore
   datastore-id CDATA #REQUIRED 
   chunk-size CDATA #IMPLIED
   freeze-size CDATA #IMPLIED
   freeze-timeout CDATA #IMPLIED
>
<!ELEMENT SystemObserverRegistrationDataStore.datastore EMPTY>
<!ATTLIST SystemObserverRegistrationDataStore.datastore
   datastore-id CDATA #REQUIRED 
   chunk-size CDATA #IMPLIED
   freeze-size CDATA #IMPLIED
   freeze-timeout CDATA #IMPLIED
>
<!ELEMENT EventReportDataStore.datastore EMPTY>
<!ATTLIST EventReportDataStore.datastore
   datastore-id CDATA #REQUIRED 
   chunk-size CDATA #IMPLIED
   freeze-size CDATA #IMPLIED
   freeze-timeout CDATA #IMPLIED
>
<!ELEMENT EventNotifierDataStore.datastore EMPTY>
<!ATTLIST EventNotifierDataStore.datastore
   datastore-id CDATA #REQUIRED 
   chunk-size CDATA #IMPLIED
   freeze-size CDATA #IMPLIED
   freeze-timeout CDATA #IMPLIED
>
<!ELEMENT ServiceDefsDataStore.datastore EMPTY>
<!ATTLIST ServiceDefsDataStore.datastore
   datastore-id CDATA #REQUIRED 
   chunk-size CDATA #IMPLIED
   freeze-size CDATA #IMPLIED
   freeze-timeout CDATA #IMPLIED
>
<!ELEMENT RunsetDataStore.datastore EMPTY>
<!ATTLIST RunsetDataStore.datastore
   datastore-id CDATA #REQUIRED 
   chunk-size CDATA #IMPLIED
   freeze-size CDATA #IMPLIED
   freeze-timeout CDATA #IMPLIED
>

<!ELEMENT fault-tolerance (datastores)>

<!ELEMENT datastores (ManagedElementDataStore.datastore, 
                      SystemDataStore.datastore,
                      HostDataStore.datastore,
                      ApplicationDataStore.datastore,
                      ProcessDataStore.datastore,
                      EntityDataStore.datastore,
                      SystemObserverRegistrationDataStore.datastore,
                      EventReportDataStore.datastore,
                      EventNotifierDataStore.datastore,
                      ServiceDefsDataStore.datastore,
                      RunsetDataStore.datastore)>
<!ATTLIST datastores
   max-transaction-in-progress CDATA #REQUIRED
   max-transaction-done CDATA #REQUIRED
   cohort-timeout CDATA #REQUIRED
   coordinator-timeout CDATA #REQUIRED
   number-of-scheduler-thread CDATA #REQUIRED
   chunk-size CDATA #REQUIRED
   freeze-size CDATA #REQUIRED
   freeze-timeout CDATA #REQUIRED
>
<!ATTLIST fault-tolerance
   request-duration-policy CDATA #REQUIRED
   client-id CDATA #REQUIRED
>

=== jmnb-sdbg-edi/cardamom/tags/CARDAMOM_V2_1_CE/SystemMngt/valid/validationdata/data/CdmwSystemMngtDatastoreConfig.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- ===================================================================== -->
<!--
 * This file is part of CARDAMOM (R) which is jointly developed by THALES
 * and SELEX-SI. It is derivative work based on PERCO Copyright (C) THALES
 * 2000-2003. All rights reserved.
 * 
 * Copyright (C) THALES 2004-2005. All rights reserved
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Library General Public License as published
 * by the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Library General Public
 * License along with CARDAMOM; see the file COPYING. If not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
-->
<!-- ===================================================================== -->

<!DOCTYPE process SYSTEM "CdmwSystemMngtDatastore_Desc.dtd">

<process>
    <services>
        <fault-tolerance request-duration-policy="50000" client-id="FTSystemMngt">
            <datastores max-transaction-in-progress="10" 
                max-transaction-done="20" 
                cohort-timeout="4000"
                coordinator-timeout="4000"
                number-of-scheduler-thread="5"
                chunk-size="200"
                freeze-size="150"
                freeze-timeout="500">
                <ManagedElementDataStore.datastore datastore-id="1"/>
                <SystemDataStore.datastore datastore-id="2"/>
                <HostDataStore.datastore datastore-id="3"/>
                <ApplicationDataStore.datastore datastore-id="4"/>
                <ProcessDataStore.datastore datastore-id="5"/>
                <EntityDataStore.datastore datastore-id="6"/>
                <SystemObserverRegistrationDataStore.datastore datastore-id="7"/>
                <EventReportDataStore.datastore datastore-id="8"/>
                <EventNotifierDataStore.datastore datastore-id="9"/>
                <ServiceDefsDataStore.datastore datastore-id="10"/>
                <RunSetDataStore.datastore datastore-id="11"/>
            </datastores>
        </fault-tolerance>
    </services>
</process>
