=== jmnb-sdbg-edi/cardamom/trunk/SystemMngt/platformadmin/c++/data/CdmwPlatformMngtSystem.dtd
<!-- ===================================================================== -->
<!--
 * This file is part of CARDAMOM (R) which is jointly developed by THALES
 * and SELEX-SI. It is derivative work based on PERCO Copyright (C) THALES
 * 2000-2003. All rights reserved.
 * 
 * Copyright (C) THALES 2004-2005. All rights reserved
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Library General Public License as published
 * by the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Library General Public
 * License along with CARDAMOM; see the file COPYING. If not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
-->
<!-- ===================================================================== -->

<!-- Perco deployment file DTD (Thales ISR ) -->

<!-- ***************** -->
<!-- System definition -->
<!-- ***************** -->
<!ELEMENT System (
    Timeout,
    Host-monitoring,
    App-monitoring,
    Proc-monitoring,
    Service*,
    Entity*,
    Host*,
    Application*,
    Init-graph?,
    Stop-graph?,
    Run-set*,
    Property* )>
<!ATTLIST System
    Name CDATA #REQUIRED
	Port CDATA #REQUIRED
>

<!-- ******************************** -->
<!-- Timeout definition for processes -->
<!-- ******************************** -->
<!ELEMENT Timeout EMPTY>
<!ATTLIST Timeout
	Init CDATA #REQUIRED
	Run  CDATA #REQUIRED
	Stop CDATA #REQUIRED
>

<!-- ************************** -->
<!-- Host monitoring definition -->
<!-- ************************** -->
<!ELEMENT Host-monitoring EMPTY>
<!ATTLIST Host-monitoring
    Pull-interval CDATA #REQUIRED
    Pull-timeout  CDATA #REQUIRED
>


<!-- *************************  -->
<!--    Property definition     -->
<!-- *************************  -->

<!ELEMENT Property EMPTY>
<!ATTLIST Property
	Name  CDATA #REQUIRED
	Type  (Short|Float|String) #REQUIRED
	Value CDATA #IMPLIED
	Mode  CDATA #IMPLIED 
>
   
<!-- ********************************* -->
<!-- Application monitoring definition -->
<!-- ********************************* -->
<!ELEMENT App-monitoring EMPTY>
<!ATTLIST App-monitoring
    Pull-interval CDATA #REQUIRED
    Pull-timeout  CDATA #REQUIRED
>

<!-- ***************************** -->
<!-- Process monitoring definition -->
<!-- ***************************** -->
<!ELEMENT Proc-monitoring EMPTY>
<!ATTLIST Proc-monitoring
    Model ( NO_MONITORING |
            PULL_MONITORING |
            PUSH_MONITORING |
            FULL_MONITORING )
            #REQUIRED
    Pull-interval CDATA #REQUIRED
    Pull-timeout  CDATA #REQUIRED
    Push-interval CDATA #REQUIRED
    Push-timeout  CDATA #REQUIRED
>

<!-- ****************** -->
<!-- Service definition -->
<!-- ****************** -->
<!ELEMENT Service EMPTY>
<!ATTLIST Service
	Name         CDATA #REQUIRED
	App-name     CDATA #REQUIRED
	Process-name CDATA #REQUIRED
	Host-name    CDATA #IMPLIED
>

<!-- ***************** -->
<!-- Entity definition -->
<!-- ***************** -->
<!ELEMENT Entity ( Property* )>
<!ATTLIST Entity
	Name CDATA #REQUIRED
>

<!-- *************** -->
<!-- Host definition -->
<!-- *************** -->
<!ELEMENT Host (
    Host-monitoring?,
    Entity*,
    Property* )>
<!ATTLIST Host
	Name            CDATA #REQUIRED
	App-exec-path   CDATA #IMPLIED
	Agent-exec-path CDATA #IMPLIED
>

<!-- ********************** -->
<!-- Application definition -->
<!-- ********************** -->
<!ELEMENT Application (
    Timeout?,
    App-monitoring?,
    Proc-monitoring?,
    Service*,
    Entity*,
    ( Managed-process | Unmanaged-process )*,
    Init-graph?,
    Stop-graph?,
    Property* )>
<!ATTLIST Application
	Name          CDATA #REQUIRED
    Host-name     CDATA #IMPLIED
    Agent-port    CDATA #IMPLIED
    Agent-args    CDATA #IMPLIED
    Agent-run-dir CDATA #IMPLIED
    App-port      CDATA #IMPLIED
    App-args      CDATA #IMPLIED
    App-run-dir   CDATA #IMPLIED
>

<!-- ************************** -->
<!-- Managed process definition -->
<!-- ************************** -->
<!ELEMENT Managed-process (
    Init-step+,
    Run-timeout?,
    Stop-timeout?,
    Proc-monitoring?,
    Service*,
    Entity*,
    Property* )>
<!ATTLIST Managed-process
	Name      CDATA #REQUIRED
	Host-name CDATA #REQUIRED
	Type      ( MANAGED-PROCESS |
                SERVICE-PROVIDER |
                COMPONENT-SERVER )
                #REQUIRED
	Autoended ( FALSE | TRUE ) #REQUIRED
	Exec-path CDATA #REQUIRED
    Port      CDATA #IMPLIED
	Args      CDATA #IMPLIED
	Run-dir   CDATA #IMPLIED
>

<!-- ******************** -->
<!-- Init step definition -->
<!-- ******************** -->
<!ELEMENT Init-step EMPTY>
<!ATTLIST Init-step
	Name    CDATA #REQUIRED
    Timeout CDATA #IMPLIED
>

<!-- ********************** -->
<!-- Run timeout definition -->
<!-- ********************** -->
<!ELEMENT Run-timeout EMPTY>
<!ATTLIST Run-timeout
    Timeout CDATA #REQUIRED
>

<!-- *********************** -->
<!-- Stop timeout definition -->
<!-- *********************** -->
<!ELEMENT Stop-timeout EMPTY>
<!ATTLIST Stop-timeout
    Timeout CDATA #REQUIRED
>

<!-- *************************** -->
<!-- Unamaged process definition -->
<!-- *************************** -->
<!ELEMENT Unmanaged-process ( Property* )>
<!ATTLIST Unmanaged-process
	Name      CDATA #REQUIRED
	Host-name CDATA #REQUIRED
	Autoended ( FALSE | TRUE ) #REQUIRED
	Exec-path CDATA #REQUIRED
	Port      CDATA #IMPLIED
	Args      CDATA #IMPLIED
	Run-dir   CDATA #IMPLIED
>

<!-- *************************** -->
<!-- Dependency graph definition -->
<!-- *************************** -->
<!ELEMENT Init-graph (
    Graph-element+,
    Graph-element-root+ )>
    
<!ELEMENT Stop-graph (
    Graph-element+,
    Graph-element-root+ )>
    
<!ELEMENT Graph-element (
    Graph-element-successor* )>
<!ATTLIST Graph-element
	Name CDATA #REQUIRED
	Host CDATA #IMPLIED
	Step CDATA #IMPLIED
>

<!ELEMENT Graph-element-successor EMPTY>
<!ATTLIST Graph-element-successor
	Name CDATA #REQUIRED
	Host CDATA #IMPLIED
	Step CDATA #IMPLIED
>

<!ELEMENT Graph-element-root EMPTY>
<!ATTLIST Graph-element-root
	Name CDATA #REQUIRED
	Host CDATA #IMPLIED
	Step CDATA #IMPLIED
>

<!-- ****************** -->
<!-- Run set definition -->
<!-- ****************** -->
<!ELEMENT Run-set (
    Run-set-element+ )>
<!ATTLIST Run-set
	Name CDATA #REQUIRED
>
<!ELEMENT Run-set-element EMPTY>
<!ATTLIST Run-set-element
    Name CDATA #REQUIRED
>

<!-- ******************************* -->
<!-- Additional definitions used for -->
<!-- hot process modification        -->
<!-- ******************************* -->
<!ELEMENT Life-cycle (
    Init-step+,
    Run-timeout,
    Stop-timeout )>

=== jmnb-sdbg-edi/cardamom/trunk/TraceAndPerf/valid/validationdata/data/V-TRC-007-1.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- ===================================================================== -->
<!--
 * This file is part of CARDAMOM (R) which is jointly developed by THALES
 * and SELEX-SI. It is derivative work based on PERCO Copyright (C) THALES
 * 2000-2003. All rights reserved.
 * 
 * Copyright (C) THALES 2004-2005. All rights reserved
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Library General Public License as published
 * by the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Library General Public
 * License along with CARDAMOM; see the file COPYING. If not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
-->
<!-- ===================================================================== -->


<!DOCTYPE System SYSTEM "CdmwPlatformMngtSystem.dtd">

<!-- ***************** -->
<!-- System definition -->
<!--                   -->
<!-- ***************** -->
<System Name="Validation" Port="21869">

    <!-- Default timeouts for processes of the entire system -->
	<Timeout Init="20000" Run="20000" Stop="20000"/>

    <!-- Default monitorings for the entire system -->
	<Host-monitoring Pull-interval="1000" Pull-timeout="1500"/>
	<App-monitoring  Pull-interval="060" Pull-timeout="070"/>
    <Proc-monitoring Model="NO_MONITORING"
                     Pull-interval="021" Pull-timeout="031"
                     Push-interval="041" Push-timeout="051"/>

    <!-- Services of the system -->
	<Service Name="NamingAndRepositoryService"
             App-name="CdmwServices"
             Process-name="Repository"/>
				 

    <!-- Hosts of the system -->
	<Host Name="@hostname1val@"
          App-exec-path="cdmw_platform_application"
          Agent-exec-path="cdmw_platform_agent"/>

	<Host Name="@hostname2val@"
          App-exec-path="cdmw_platform_application"
          Agent-exec-path="cdmw_platform_agent">
	    <Host-monitoring Pull-interval="2000" Pull-timeout="2500"/>
    </Host>

    <!-- ********************** -->
    <!-- Application definition -->
    <!--                        -->
    <!-- ********************** -->
	<Application Name="CdmwServices"
                 Host-name="localhost"
                 Agent-port="-1"
                 App-port="-1">

        <!-- Default timeouts for processes of this application -->
	    <Timeout Init="20000" Run="20000" Stop="20000"/>

        <!-- Monitoring of this application -->
    	<App-monitoring Pull-interval="021" Pull-timeout="031"/>


        <!-- ******************* -->
        <!-- Process definitions -->
        <!--                     -->
        <!-- ******************* -->
		<Managed-process Name="Repository"
                         Host-name="@hostname1val@"
                         Type="SERVICE-PROVIDER"
                         Autoended="FALSE"
                         Exec-path="cdmw_naming_and_repository"
                         Args="--id=GlobalRepository --conf=cdmw_nar_integ.xml"
                         Port="22456">
			<Init-step Name="initialisation" Timeout="10000"/>
			<Run-timeout Timeout="10000"/>
			<Stop-timeout Timeout="10000"/>
		</Managed-process>

		<!-- ************************** -->
        <!--                            -->
        <!-- End of process definitions -->
        <!-- ************************** -->

        <!-- Init graph of processes of this application -->
                <Init-graph>
            <Graph-element Name="Repository">
            </Graph-element>
            <Graph-element-root Name="Repository"/>
        </Init-graph>

    <!-- ***************************** -->
    <!--                               -->
    <!-- End of application definition -->
    <!-- ***************************** -->
	</Application>


	<!-- ********************** -->
    <!-- Application definition -->
    <!--                        -->
    <!-- ********************** -->
	<Application Name="Collector"
                 Host-name="@hostname1val@"
                 Agent-port="-1"
                 App-port="-1">

        <!-- Default timeouts for processes of this application -->
	    <Timeout Init="20000" Run="20000" Stop="20000"/>

        <!-- Monitoring of this application -->
    	<App-monitoring Pull-interval="021" Pull-timeout="031"/>


        <!-- ******************* -->
        <!-- Process definitions -->
        <!--                     -->
        <!-- ******************* -->
		<Managed-process Name="TraceCollector"
                         Host-name="@hostname2val@"
                         Type="MANAGED-PROCESS"
                         Autoended="FALSE"
                         Exec-path="cdmw_trace_collector"
                         Args="--collector-name=test_collector --traceFile-name=trace_log --trace-format=H --traceBkpFile-number=2 --traceFile-number=3 --traceMessage-number=10"
                         Port="-1">
			<Init-step Name="initialisation" Timeout="10000"/>
			<Run-timeout Timeout="10000"/>
			<Stop-timeout Timeout="10000"/>
		</Managed-process>

		<!-- ************************** -->
        <!--                            -->
        <!-- End of process definitions -->
        <!-- ************************** -->

        <!-- Init graph of processes of this application -->
                <Init-graph>
            <Graph-element Name="TraceCollector">
            </Graph-element>
            <Graph-element-root Name="TraceCollector"/>
        </Init-graph>

    <!-- ***************************** -->
    <!--                               -->
    <!-- End of application definition -->
    <!-- ***************************** -->
	</Application>


	 <!-- ********************** -->
    <!-- Application definition -->
    <!--                        -->
    <!-- ********************** -->
	<Application Name="TraceTest"
                 Host-name="@hostname2val@"
                 Agent-port="-1"
                 App-port="-1">

        <!-- Default timeouts for processes of this application -->
	    <Timeout Init="20000" Run="20000" Stop="20000"/>

        <!-- Monitoring of this application -->
    	<App-monitoring Pull-interval="021" Pull-timeout="031"/>

        <!-- ******************* -->
        <!-- Process definitions -->
        <!--                     -->
        <!-- ******************* -->

		<Managed-process Name="TraceClient"
		                 Host-name="@hostname2val@"
					     Type="MANAGED-PROCESS"
                         Autoended="FALSE"
                         Exec-path="cdmw_trace_client_3"
					     Args="--trace-nbr=15 --collector-name=test_collector"
					     Port="-1">
			<Init-step Name="initialisation" Timeout="8000"/>
			<Run-timeout Timeout="10000"/>
			<Stop-timeout Timeout="2000"/>
		</Managed-process>

        <!-- ************************** -->
        <!--                            -->
        <!-- End of process definitions -->
        <!-- ************************** -->

		<!-- Init graph of processes of this application -->
        <Init-graph>
            <Graph-element Name="TraceClient">
            </Graph-element>
            <Graph-element-root Name="TraceClient"/>
        </Init-graph>


    <!-- ***************************** -->
    <!--                               -->
    <!-- End of application definition -->
    <!-- ***************************** -->
	</Application>


    <!-- Init graph of applications of the system-->
    <Init-graph>
        <Graph-element Name="CdmwServices"> 
            <Graph-element-successor Name="Collector"/>
        </Graph-element>
        <Graph-element Name="Collector"> 
            <Graph-element-successor Name="TraceTest"/>
        </Graph-element>
        <Graph-element Name="TraceTest"> 
        </Graph-element>
        <Graph-element-root Name="CdmwServices"/> 
    </Init-graph>

</System>
<!-- ************************ -->
<!--                          -->
<!-- End of system definition -->
<!-- ************************ -->

=== jmnb-sdbg-edi/cardamom/trunk/SystemMngt/platformapplicationlibrary/test/teststdattributes_Process_Managed/c++/data/HelloSystemDefinition.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- ===================================================================== -->
<!--
 * This file is part of CARDAMOM (R) which is jointly developed by THALES
 * and SELEX-SI. It is derivative work based on PERCO Copyright (C) THALES
 * 2000-2003. All rights reserved.
 * 
 * Copyright (C) THALES 2004-2005. All rights reserved
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Library General Public License as published
 * by the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Library General Public
 * License along with CARDAMOM; see the file COPYING. If not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
-->
<!-- ===================================================================== -->


<!DOCTYPE System SYSTEM "./CdmwPlatformMngtSystem.dtd">

<!-- ***************** -->
<!-- System definition -->
<!--                   -->
<!-- ***************** -->

<System Name="MySystem" Port="21869">

	<!-- Default timeouts for processes of the entire system -->
	<Timeout Init="20000" Run="20000" Stop="20000"/>
	<!-- Default monitorings for the entire system -->
	<Host-monitoring Pull-interval="1000" Pull-timeout="1500"/>
	<App-monitoring Pull-interval="060" Pull-timeout="070"/>
	<Proc-monitoring Model="NO_MONITORING" 
	                 Pull-interval="021" Pull-timeout="031" 
	                 Push-interval="041" Push-timeout="051"/>
	
	
	<!-- Hosts of the system -->
	<Host Name="@host_name@"  >
		<Host-monitoring Pull-interval="2000" Pull-timeout="2500"/>
	</Host>
	
	<!-- ********************** -->
	<!-- Application definition -->
	<!--                        -->
	<!-- ********************** -->
	<Application Name="HELLO_WORLD" 
	             Host-name="@host_name@" 
	             Agent-port="-1" 
	             App-port="-1">
	             
		<!-- Default timeouts for processes of this application -->
		<Timeout Init="20000" Run="20000" Stop="20000"/>
		
		<!-- Monitoring of this application -->
		<App-monitoring Pull-interval="021" Pull-timeout="031"/>
		
		<!-- ******************* -->
		<!-- Process definitions -->
		<!--                     -->
		<!-- ******************* -->

        <Managed-process Name="HelloProcess1"
                     Host-name="@host_name@" 
                     Type="MANAGED-PROCESS"
                     Autoended="TRUE" 
                     Exec-path="proc1.csh" 
                     Args=""
                     Port="-1" >
            <Init-step Name="step0" Timeout="10000"/>
        </Managed-process> 
 

		<!-- ************************** -->
		<!--                            -->
		<!-- End of process definitions -->
		<!-- ************************** -->
		
		<!-- Init graph of processes of this application -->
		<Init-graph>
		    <Graph-element Name="HelloProcess1">
			</Graph-element>
			<Graph-element-root Name="HelloProcess1"/>
		</Init-graph>
		
		<!-- ***************************** -->
		<!--                               -->
		<!-- End of application definition -->
		<!-- ***************************** -->
	</Application>
	
	
	<!-- Stop graph of applications of the system-->
	
	<Init-graph>
		    <Graph-element Name="HELLO_WORLD">
			</Graph-element> 
			<Graph-element-root Name="HELLO_WORLD"/>
	</Init-graph>
	
	<Stop-graph>
		<Graph-element Name="HELLO_WORLD">
		</Graph-element>
		<Graph-element-root Name="HELLO_WORLD"/>
	</Stop-graph> 

	
</System>

<!-- ************************ -->
<!--                          -->
<!-- End of system definition -->
<!-- ************************ -->

=== jmnb-sdbg-edi/cardamom/trunk/SystemMngt/platformsystemlibrary/test/testnavigability/c++/data/HelloSystemDefinition.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- ===================================================================== -->
<!--
 * This file is part of CARDAMOM (R) which is jointly developed by THALES
 * and SELEX-SI. It is derivative work based on PERCO Copyright (C) THALES
 * 2000-2003. All rights reserved.
 * 
 * Copyright (C) THALES 2004-2005. All rights reserved
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Library General Public License as published
 * by the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Library General Public
 * License along with CARDAMOM; see the file COPYING. If not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
-->
<!-- ===================================================================== -->


<!DOCTYPE System SYSTEM "./CdmwPlatformMngtSystem.dtd">

<!-- ***************** -->
<!-- System definition -->
<!--                   -->
<!-- ***************** -->

<System Name="MySystem" Port="21869">

	<!-- Default timeouts for processes of the entire system -->
	<Timeout Init="20000" Run="20000" Stop="20000"/>
	<!-- Default monitorings for the entire system -->
	<Host-monitoring Pull-interval="1000" Pull-timeout="1500"/>
	<App-monitoring Pull-interval="060" Pull-timeout="070"/>
	<Proc-monitoring Model="NO_MONITORING" 
	                 Pull-interval="021" Pull-timeout="031" 
	                 Push-interval="041" Push-timeout="051"/>
	
	<!-- Services of the system -->
	<!-- <Service Name="NamingAndRepositoryService" 
	         App-name="CardamomServices" 
	         Process-name="Repository"/>  -->
            <!--	     
	      App-exec-path="/home/florenna/MINICARDAMOM_DEVELOP/CARDAMOM_INSTALLED/bin/cdmw_platform_application" 
	      Agent-exec-path="/home/florenna/MINICARDAMOM_DEVELOP/CARDAMOM_INSTALLED/bin/cdmw_platform_agent" 
	      Probe-exec-path="/home/florenna/MINICARDAMOM_DEVELOP/CARDAMOM_INSTALLED/bin/cdmw_host_probe">
	      -->
	
	<!-- Hosts of the system -->
	<Host Name="@host_name@"  >
		<Host-monitoring Pull-interval="2000" Pull-timeout="2500"/>
	</Host>
	
	<!-- ********************** -->
	<!-- Application definition -->
	<!--                        -->
	<!-- ********************** -->
	<Application Name="HELLO_WORLD" 
	             Agent-port="-1" 
	             App-port="-1">
	             
		<!-- Default timeouts for processes of this application -->
		<Timeout Init="20000" Run="20000" Stop="20000"/>
		
		<!-- Monitoring of this application -->
		<App-monitoring Pull-interval="021" Pull-timeout="031"/>
		
		<!-- ******************* -->
		<!-- Process definitions -->
		<!--                     -->
		<!-- ******************* -->
               <Unmanaged-process Name="HelloProcess1"
                     Host-name="@host_name@" 
                     Autoended="TRUE" 
                     Exec-path="./proc1.csh"
		     Port="-1" />
		     

               <Unmanaged-process Name="HelloProcess2"
                     Host-name="@host_name@" 
                     Autoended="TRUE" 
                     Exec-path="./proc2.csh"
		     Port="-1" />
		    

               <Unmanaged-process Name="HelloProcess3"
                     Host-name="@host_name@" 
                     Autoended="TRUE" 
                     Exec-path="./proc3.csh"
		     Port="-1" />
		   
		
		<!-- ************************** -->
		<!--                            -->
		<!-- End of process definitions -->
		<!-- ************************** -->
		
		<!-- Init graph of processes of this application -->
		<Init-graph>
		    <Graph-element Name="HelloProcess1">
			<Graph-element-successor Name="HelloProcess2"  />
			</Graph-element> 

		    <Graph-element Name="HelloProcess2">
			<Graph-element-successor Name="HelloProcess3"  />
			</Graph-element> 

			<Graph-element-root Name="HelloProcess1"/>
		</Init-graph>
		
		<!-- ***************************** -->
		<!--                               -->
		<!-- End of application definition -->
		<!-- ***************************** -->
	</Application>
	
	
	<!-- Stop graph of applications of the system-->
	
	<Init-graph>
		    <Graph-element Name="HELLO_WORLD">
			</Graph-element> 
			<Graph-element-root Name="HELLO_WORLD"/>
	</Init-graph>
	
	<Stop-graph>
		<Graph-element Name="HELLO_WORLD">
		</Graph-element>
		<Graph-element-root Name="HELLO_WORLD"/>
	</Stop-graph> 

<!-- Run sets of the system -->
<!--
<Run-set Name="RS1">
  <Run-set-element Name="HelloProcess1"/>
  <Run-set-element Name="HelloProcess2"/>
  <Run-set-element Name="HelloProcess3"/>
</Run-set>
-->
	
	
</System>

<!-- ************************ -->
<!--                          -->
<!-- End of system definition -->
<!-- ************************ -->
