=== jmnb-sdbg-edi/cardamom/trunk/SystemMngt/platformdaemon/c++/data/CdmwPlatformMngtDaemon.dtd
<!-- ===================================================================== -->
<!--
 * This file is part of CARDAMOM (R) which is jointly developed by THALES
 * and SELEX-SI. It is derivative work based on PERCO Copyright (C) THALES
 * 2000-2003. All rights reserved.
 * 
 * Copyright (C) THALES 2004-2005. All rights reserved
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Library General Public License as published
 * by the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Library General Public
 * License along with CARDAMOM; see the file COPYING. If not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
-->
<!-- ===================================================================== -->

<!--DTD specifying parameters for the CDMW PlatformManagement Daemon-->
<!--Port identifying the system-->
<!ELEMENT SystemPort (#PCDATA)>
<!--The user id used for creating processes through the daemon-->
<!ELEMENT UID (#PCDATA)>
<!--The group id used for creating processes through the daemon-->
<!ELEMENT GID (#PCDATA)>
<!--Full path to the log file-->
<!ELEMENT LogFile (#PCDATA)>
<!--Full path to the file containing the IOR of the daemon-->
<!ELEMENT IorFile (#PCDATA)>
<!--The timeout in ms allowed for notifying a platform information-->
<!ELEMENT NotificationCallTimeout (#PCDATA)>
<!--The interval in ms for pull monitoring-->
<!ELEMENT PullMonitoringInterval (#PCDATA)>
<!--The timeout in ms allowed for pull monitoring-->
<!ELEMENT PullMonitoringTimeout (#PCDATA)>
<!--The directory with the files containing pid of launched processes-->
<!--If not specified, /tmp/CdmwDaemon_<SystemPort> is used-->
<!ELEMENT ProcessesIdDirectory (#PCDATA)>
<!--The request duration time - only used with fault tolerance-->
<!ELEMENT RequestDurationTime (#PCDATA)>
<!--The SIMPLE_PULL_CORBALOC - only used with fault tolerance and for the simple monitoring-->
<!ELEMENT SimplePullCorbaloc (#PCDATA)>
<!--The SIMPLE_PUSH_CORBALOC - only used with fault tolerance and for the simple monitoring-->
<!ELEMENT SimplePushCorbaloc (#PCDATA)>
<!--The Service Locator configuration-->
<!ELEMENT ServiceLocator EMPTY>
<!ATTLIST ServiceLocator
    address CDATA #REQUIRED
    nb-retries CDATA #REQUIRED
    time-intervale CDATA #REQUIRED
>
<!ELEMENT CdmwPlatformMngtDaemon (SystemPort, UID, GID, LogFile, IorFile, ServiceLocator, NotificationCallTimeout?, PullMonitoringInterval?, PullMonitoringTimeout?, ProcessesIdDirectory?,RequestDurationTime?, SimplePullCorbaloc?, SimplePushCorbaloc?)>

=== jmnb-sdbg-edi/cardamom/trunk/ProdTests/qualif/common/data/CdmwPlatformMngtDaemon_conf.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
 * =========================================================================== *
 * This file is part of CARDAMOM (R) which is jointly developed by THALES
 * and SELEX-SI.
 * 
 * It is derivative work based on PERCO Copyright (C) THALES 2000-2003.
 * All rights reserved.
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Library General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your
 * option) any later version.
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Library General
 * Public License along with CARDAMOM; see the file COPYING. If not, write to
 * the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 * =========================================================================== *
-->

<!DOCTYPE CdmwPlatformMngtDaemon SYSTEM "CdmwPlatformMngtDaemon.dtd">

<CdmwPlatformMngtDaemon>
	<SystemPort>21869</SystemPort>
	<UID>-1</UID>
	<GID>-1</GID>
	<LogFile>CdmwDaemon.log</LogFile>
	<IorFile>CdmwDaemon.ior</IorFile>
	<NotificationCallTimeout>10000</NotificationCallTimeout>
    <RequestDurationTime>20000000</RequestDurationTime>
    <SimplePullCorbaloc>corbaloc:miop:1.0@1.0-cdmw_ftdomain-1/225.1.1.8:4556</SimplePullCorbaloc>
    <SimplePushCorbaloc>corbaloc:miop:1.0@1.0-cdmw_ftdomain-2/225.1.1.8:4557</SimplePushCorbaloc>
</CdmwPlatformMngtDaemon>
