=== jmnb-sdbg-edi/cardamom/branches/InitialVersion/FaultTolerance/ftmanager/test/testfaultdetector/c++/data/CdmwFaultToleranceGroupCreator.dtd
<!-- ===================================================================== -->
<!--
 * This file is part of CARDAMOM (R) which is jointly developed by THALES
 * and SELEX-SI. It is derivative work based on PERCO Copyright (C) THALES
 * 2000-2003. All rights reserved.
 * 
 * Copyright (C) THALES 2004-2005. All rights reserved
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Library General Public License as published
 * by the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Library General Public
 * License along with CARDAMOM; see the file COPYING. If not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
-->
<!-- ===================================================================== -->

<!--DTD specifying parameters for the CDMW fault manager-->
<!ELEMENT groups (object-group*)>

<!ELEMENT object-group (locations, datastoreIDs?)>
<!ATTLIST object-group 
    name CDATA #REQUIRED
	type-id CDATA #REQUIRED
	minimum-number-replicas CDATA #REQUIRED
>
 
<!ELEMENT locations (location*)>
<!ELEMENT location EMPTY>
<!ATTLIST location 
    host-name CDATA #REQUIRED
    application-name CDATA #IMPLIED
    process-name CDATA #REQUIRED
>

<!ELEMENT datastoreIDs (datastoreID*)>
<!ELEMENT datastoreID EMPTY>
<!ATTLIST datastoreID 
    id CDATA #REQUIRED
>

=== jmnb-sdbg-edi/cardamom/branches/InitialVersion/FaultTolerance/ftgroupcreator/c++/data/CdmwFaultToleranceGroupCreator_conf.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- ===================================================================== -->
<!--
 * This file is part of CARDAMOM (R) which is jointly developed by THALES
 * and SELEX-SI. It is derivative work based on PERCO Copyright (C) THALES
 * 2000-2003. All rights reserved.
 * 
 * Copyright (C) THALES 2004-2005. All rights reserved
 * 
 * CARDAMOM is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Library General Public License as published
 * by the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * CARDAMOM is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE. See the GNU Library General Public
 * License for more details.
 * 
 * You should have received a copy of the GNU Library General Public
 * License along with CARDAMOM; see the file COPYING. If not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
-->
<!-- ===================================================================== -->
<!--<!DOCTYPE groups SYSTEM "CdmwFaultToleranceGroupCreator.dtd">-->

<groups>
	<object-group name="Naming" type-id="the naming type id" minimum-number-replicas="4">
		<locations>
			<location host-name="host1" application-name="APPL1" process-name="P1"/>
			<location host-name="host2" application-name="APPL2" process-name="P2"/>
		</locations>
		<datastoreIDs>
			<datastoreID id=""/>
			<datastoreID id=""/>
		</datastoreIDs>
	</object-group>
	<object-group name="Repository" type-id="the repository type id" minimum-number-replicas="2">
		<locations>
			<location host-name="host3" application-name="APPL3" process-name="P3"/>
			<location host-name="host4" application-name="APPL4" process-name="P4"/>
			<location host-name="host5" application-name="APPL5" process-name="P5"/>
		</locations>
	</object-group>
</groups>
